// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bbfffe88-9ea2-445d-b400-666b61685c18",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_uGvZla5ca",
    "aws_user_pools_web_client_id": "15qcef58pslib1ruj23fcqvib0"
};


export default awsmobile;
